Browser=Chrome
Browser.Version=120.0
Playwright.Version=1.54.1
Platform=Windows 11
TestedBy=Satish QA
TestEnv=Staging
Timezone=Africa/Johannesburg
Node.Version=22.2.0
Execution=PASSED
Categories=No issues found
Build=QA Automation